export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SERIES_SUCCESS = 'LOAD_SERIES_SUCCESS';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_TV_CHANNELS_SUCCESS = 'LOAD_TV_CHANNELS_SUCCESS';
export const UPDATE_SERIES_SUCCESS = 'UPDATE_SERIES_SUCCESS';
export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS';
export const UPDATE_CHANNELS_SUCCESS = 'UPDATE_CHANNELS_SUCCESS';
export const UPDATE_TV_CHANNELS_SUCCESS = 'UPDATE_TV_CHANNELS_SUCCESS';